### ISSUE TITLE
1.21.3 support?

### ISSUE THREAD

**Issue by Arden-Ahmad** [fantahund/cr3stal#2]
I really like your mod :)

**Comment by fantahund** [comment]
Mojang has changed the rendering of EndCrystal so much that it is currently not so easy. i would really have to rebuild a lot to make it work again, i don't have time for that at the moment because other mods need more attention.
If I have time I will update it but if someone has time and desire before I also accept Pull Requests. ^^
![Moose2982](https://github.com/user-attachments/assets/249d9ceb-8439-4123-8544-a0ca0e2841f5)

**Comment by fantahund** [comment]
Done -> [Modrinth](https://modrinth.com/mod/crestal/version/Vx8bipEP)
